name: release
on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: version
        id: version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: Cargo.toml
          field: package.version
      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ steps.version.outputs.value }}
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: publish to crates.io
        run: cargo publish -p streamstore --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.value }}
          body: ${{ steps.changelog_reader.outputs.changes }}
