name: Update protos

permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types: [s2-proto-update]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Update Submodules
        id: submodules
        uses: sgoudham/update-git-submodules@v2.1.1
        with:
          submodules: proto

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable nightly
          components: rustfmt, clippy
      - name: install protoc
        uses: arduino/setup-protoc@v3    
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort
          version: "^1.0"
      - name: build protos
        run: |
          cargo build --features prost-build

      - name: Create Pull Request
        if: ${{ steps.submodules.outputs['proto--updated'] }}
        uses: peter-evans/create-pull-request@v7
        with:
          committer: s2-helper[bot] <194906454+s2-helper[bot]@users.noreply.github.com>
          author: s2-helper[bot] <194906454+s2-helper[bot]@users.noreply.github.com>
          title: chore - proto update
          branch: "proto/update-s2-protos-${{ steps.submodules.outputs['proto--latestShortCommitSha'] }}"
          body: ${{ steps.submodules.outputs.prBody }}
